### ISSUE TITLE
Texture Armor Glitch plus Solution and Suggestions

### ISSUE THREAD

**Issue by Dhenier** [mobehun/BraveTechnology#1]
Brave Technology - New World v1.16 and v1.17

I just updated to v1.17 to see if it would fix the missing textures for armor bug that me and 5 of my friends are experiencing. It did not fix the problem.

I was able to fix it by creating a new profile and updating it to forge 1.10.2 - 12.18.1.2077.

Here is a picture that shows the bug as it still exists in v1.17
http://prntscr.com/cgqb25

and how I have fixed the bug using the 1.16 mods but updated forge to 1.10.2 - 12.18.1.2077.
http://prntscr.com/cgq49k

The use of a resourcepack has no effect on the bug. I already tested that last night and I am currently the only one on our server using a resourcepack.

Some side suggestions/advice. (I've made 5 modpacks and run about 6 bukkit/spiggot servers over the last 3 years so I have a lot of experience with getting mods to play nice with each other): 
1) Disable duplicate ores whenever you can. Base Metals has added a lot or ores for Orespawn that are already present in the game from other mods. Base Metals was created to cover missing ores that Orespawn needs. I usually decide on one major mod like Thermal Expansion that I know won't change and want to use as the baseline. Then I go through and disable the duplicate ores from other mods. Forge makes the ores recipe interchangeable, but not stackable and they don't have the same textures. Just makes the modpack look more professional when you take the time to do that. Even though it is time consuming at first. I wish Thermal Expansion was up-to-date - it has an easy way to reassign ores, but oh well. 

2) Never remove mods that add world gen. That should be saved for a major update like going from v 1.10.2 to 1.11 of MC. Otherwise people who start a server with your modpack will have to restart or be faced with weird missing block areas all over the generated world area. This is one of those things that make server owners, like me, trust you as a modpack maker so I want to continue using your modpacks. What I do when deciding on mods is #1 does it add world gen along with whatever it is adding to the game - if the added game function outweighs the worldgen issue then I add it, otherwise I email the mod author and ask what their status is for updates. If they are making lots of changes and updates then I usually don't add the mod. Most authors put in a way to add worldgen at a later time, but removing it usually requires a more robust mod like Thermal Expansion. Fortunately I don't think Blood Arsenal removed any worldgen, but one consideration would be to keep Blood Magic at its original release until Blood Arsenal was updated to work with it. (Of course I am sure you emailed the author of Blood Arsenal before deciding to remove it bc he may be working on an update.)

3) Add mods that are mature and have a purpose and avoid mods that duplicate functionality (choose the best one) - all encompassing mods should only be used if they are very mature. I started getting Ameythist dust from a mod called Simple Upgrades. Amethyst dust requires an Arc Furnace to process - no Arc Furnace exists in the game and the site for simpleupgrades lists a lot of features, but no documentation. And it does not list an Arc Furnace. I'm not sure what this mod adds that other mods in the pack don't provide, but getting stuff that serves no purpose in the game is a waste of game time even if there is some future hope that the mod will be updated.

4) Veinminer has a setting that allows the server to set the keybind or the user - this should be set to user. Server admins should not have to go and change that - I don't know why the author of veinminer chose to make his base config that way, bc I am guessing you did not make that change? If something can be left to a client side decision then it should be set that way. Users like to have freedom. 

We are using your modpack because my friend chose this pack. He tried to make his own, but got bogged down in config hell and did not want me to do it for him so he went with a pre-made. I like the pack so far - we have had a lot of fun playing on it, but I think with some more tweaks it will be a better pack. 

I am not sure why we are all having this graphical glitch with the armor and you are not, but we all use Windows 10 and have different graphics cards and cpu's. 

Thank you

**Comment by mobehun** [comment]
Thank you very much for all the feedback. THIS is what I was in need of! Lots of feedback. I've not had the armor texture issue but if updating forge fixed it for you, I'll update it in the pack too.
To be honest, I did not bother with asking the author of Blood Arsenal. (I was a bit lazy...) Should I change it back? (I should, shouldn't I? :D )
Simple Upgrades ads a bunch of random item, and armor/tools. As for the Amethyst, when you break the ore, you should get Amethyst Dust (useless) but then you can smelt that in any kind of furnace and get Amethyst Ingot. The Arc Furnace is an Immersive Engineering multiblock structure (Very endgame/OP).
The thing with Veinminer is set to this: S:client.preferredMode=sneak and the reason for that is, that for me, that's the easier to use. I can't change what's the server default, just the client. It can be changed with /veinminerc disabled/pressed/released/sneak/no_sneak and then if it's set to pressed, the key can be changed in the Controls menu (default is grave).

I'm using Windows 10 too so I have no idea what caused the glitch.
If you find more bugs, please let me know.

**Comment by mobehun** [comment]
Posted an issue about the Amethyst thing.
https://github.com/Kashdeya/SimpleUpgrades/issues/47

**Comment by mobehun** [comment]
Fixed with the latest version.
