### ISSUE TITLE
Brave Technology - New World Server issue

### ISSUE THREAD

**Issue by daniel3006** [mobehun/BraveTechnology#4]
Can't start the server because of a crash. :(
[crash-2016-10-02_21.42.15-server.txt](https://github.com/mobehun/BraveTechnology/files/506185/crash-2016-10-02_21.42.15-server.txt)

**Comment by mobehun** [comment]
I've updated Bookshelf to "Bookshelf-1.10.2-1.4.2.325" and it works fine now. I'll upload the new version as soon as I test everything else.

**Comment by mobehun** [comment]
New version is up! Please test it.
