### ISSUE TITLE
Crash Report - Crash While Loading

### ISSUE THREAD

**Issue by cronicpain** [mobehun/BraveTechnology#7]
Hey so i downloaded your mod pack and tryed to load it up, but it crashed the over view crash log said it ran out of ram, this cant be caused by my comp cus i have 8gb of ram, and it said that it ran out at like 2. with that said i know that old technic packs had issues with this where the launcher itself had the option of configing how much ram each pack can use, i dont know if curse can do that or not, but if so just send me a quick replay as to how to edit that or a link to somewhere that explains in lots of detail how to do that and i will try again. I really want to try your pack out cus the other 2 packs that i have tryed for a pack that has a good mix of magic/tech that also has my fave mods that i just cant live without are a little lacking.

also i just finished downloaded the current version/ ran it but it still crashed before the main menu i havent looked at the crash report yet, going to add it to this commet it will be the second one, both for the downloand/hard copy, but i would guess that it still had something to do with ram, i did make a new profile so that i could try your earlyer version. i set it up as the first official release that you had and it loaded up just fine even let me create a new world, my sugjestion is to go through all the releases, one by one load it up and create a world, do that untill u hit a relase that crashes b4 the main menu, the go through the prereleases until you find the earlyest release that does not crash.

that would be the hard part, this is the more time consumming part, compare any  and all mods that the two profiles have, and find out any mods that have been added, hopefully it is one of thouse mods that is causeing the crash. so remove them one by one, or 1/2 of them and check each half, keep halfing the amount of mods till you isolate the mod that is causeing you to crash, then remove it/ try to load the game.

if that doesnt work then try the same thing with the rest of the mods, for me this is the quickest way to isolate a proble and then i try to fix it.

with all that said i also am including the crash log to help you out incase it wasnt the launcher, i hope that its the launchers fault, cus i dont know much about coding but if i did i would help out as much as i could, thanks for looking at this

[Crash log -  crash happend while loading the game b4 getting to main menu.txt](https://github.com/mobehun/BraveTechnology/files/537264/Crash.log.-.crash.happend.while.loading.the.game.b4.getting.to.main.menu.txt)

new relasses' crash log - 
[crash-2016-10-18_15.38.03-client - new releasse.txt](https://github.com/mobehun/BraveTechnology/files/537375/crash-2016-10-18_15.38.03-client.-.new.releasse.txt)

and just incase you cant open the file or something here is a hard copy of it

_edited by mobehun:_
http://pastebin.com/x5aEs3dW

**Comment by mobehun** [comment]
I've taken out the crashlog from your comment and used pastebin just for saving up some space.
If you launch the app and go into settings -> Minecraft tab and then search for Java Settings you should find a slider to adjust how much memory you are allocating to the game. 
![screenshot_20161019092819](https://cloud.githubusercontent.com/assets/8471727/19509302/6e0914e0-95de-11e6-9506-47a0da60fc35.png)

You will need AT LEAST 4GB allocated but I would recommend using 5-6GB.
