### ISSUE TITLE
Can't kill mobs on 1.10.2 version.

### ISSUE THREAD

**Issue by airport1000** [mobehun/BraveTechnology#8]
I don't know if it is intentional or not but I have downloaded this pack 3 time's version 2.2 and for some reason I cannot kill any mobs both passive and hostile.

**Comment by mobehun** [comment]
Have you tried it in the 2.3 version yet?

**Comment by airport1000** [comment]
I have just tried 2.3 and still can't kill mobs, could it be because I created a new world rather then playing the provided Void World?

**Comment by airport1000** [comment]
Just tried to kill mobs in the provided Void World and still no go. I can't understand it as I have several other 1.10.2 mod packs installed and none of them have this problem.

**Comment by mobehun** [comment]
What are you trying to use to kill mobs? It's weird to me too, no one mentioned something like this to me yet.

**Comment by airport1000** [comment]
I have tried empty hand, standard sword, tinkers sword, pick axe, axe and not one of them work. I can swing and hit non entity blocks with all the above, but when it's an entity my guy will not even swing.

**Comment by airport1000** [comment]
It's OK you can close this issue now. What had happened is one of the installed mods had assigned one of it's commands to the mouse 1 button which was stopping the attack command on button 1. so after removing the button 1 command from the mod that had assigned it all is working correctly now.

**Comment by mobehun** [comment]
Glad to know it's working
