### ISSUE TITLE
Project E's transmution table/tablet will not work after cross dimension

### ISSUE THREAD

**Issue by frog9394** [mobehun/BraveTechnology#9]
Project E's transmution table/tablet will not work after cross dimension. The are fixed in the recent upgrade. Will you update this modpack? Thanks for your effort!

**Comment by mobehun** [comment]
I've not been maintaining the pack for a while now because of school but I can make an update next week.

**Comment by mobehun** [comment]
Done in https://github.com/mobehun/BraveTechnology/commit/62918631cd476d2c817d52bcaecd060906432e76

**Comment by frog9394** [comment]
Thank you very much!!!! 👍
